// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwvBqcDErcFI94ZmrFAFS6HYT0O7vfmtM',
    appId: '1:125905647168:web:a633e09c393829a12f51a5',
    messagingSenderId: '125905647168',
    projectId: 'pharma-ease',
    authDomain: 'pharma-ease.firebaseapp.com',
    storageBucket: 'pharma-ease.firebasestorage.app',
    measurementId: 'G-SSX95RHZYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7hHI-FfUaiCJhPVnkau3ZGyYb5rVu7Qs',
    appId: '1:125905647168:android:71394bf7478076442f51a5',
    messagingSenderId: '125905647168',
    projectId: 'pharma-ease',
    storageBucket: 'pharma-ease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1sw2gmL0w2G_-tXAo8hHiFtHkOKG1oG4',
    appId: '1:125905647168:ios:1ad31f86e6a363692f51a5',
    messagingSenderId: '125905647168',
    projectId: 'pharma-ease',
    storageBucket: 'pharma-ease.firebasestorage.app',
    iosBundleId: 'com.example.mobileCourseFp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1sw2gmL0w2G_-tXAo8hHiFtHkOKG1oG4',
    appId: '1:125905647168:ios:1ad31f86e6a363692f51a5',
    messagingSenderId: '125905647168',
    projectId: 'pharma-ease',
    storageBucket: 'pharma-ease.firebasestorage.app',
    iosBundleId: 'com.example.mobileCourseFp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwvBqcDErcFI94ZmrFAFS6HYT0O7vfmtM',
    appId: '1:125905647168:web:d4e042682a2725542f51a5',
    messagingSenderId: '125905647168',
    projectId: 'pharma-ease',
    authDomain: 'pharma-ease.firebaseapp.com',
    storageBucket: 'pharma-ease.firebasestorage.app',
    measurementId: 'G-3G91KY92WG',
  );
}
